import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        elements: {
          formButtonPrimary: "primary",
          footerActionLink: "primary-text hover:text-red-500",
        },
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <main className="mx-auto max-w-5xl text-2xl flex gap-2 text-dark">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
